# -*- coding: utf-8 -*-
"""Day2 Homework Answers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HtkU5LwzQTReLyiCXJTON53tDUcxBOlF
"""

list1 = ["how", "was", "your", "day?"]
list1.reverse()
print(list1)

maximum  = int(input(" Please Enter the Maximum Value : ")) 

number=0 

while -1<number <= maximum<10: 
    if(number % 2 == 0):
        print(("{0}".format(number)))
    number = number + 1

